# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160322_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='participent',
        ),
        migrations.AddField(
            model_name='participation',
            name='participent',
            field=models.ManyToManyField(null=True, to='main.Participent'),
        ),
    ]
