# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160328_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
