# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registration_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='teamCollect',
            field=models.NullBooleanField(),
        ),
    ]
